# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetsChecker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key_words', models.CharField(max_length=500)),
                ('count', models.IntegerField(max_length=4)),
            ],
        ),
    ]
