# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetsChecker', '0002_filtmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtmodel',
            name='count',
            field=models.IntegerField(),
        ),
    ]
